require('dotenv').config();
const env = process.env; 

module.exports = {
    MONGO_USERNAME: env.MONGO_USERNAME,
    MONGO_PASSWORD: env.MONGO_PASSWORD,
    MONGO_HOST: env.MONGO_HOST,
    MONGO_DBNAME: env.MONGO_DBNAME,
    SECRET_KEY:env.SECRET_KEY,
    CLOUDINARY_NAME:env.CLOUDINARY_NAME,
    CLOUDINARY_API_KEY:env.CLOUDINARY_API_KEY,
    CLOUDINARY_API_SECRET:env.CLOUDINARY_API_SECRET,
    EMAIL_SENDER: env.EMAIL_SENDER,
    EMAIL_SENDER_PASS: env.EMAIL_SENDER_PASS,
    EMAIL_SERVICE: env.EMAIL_SERVICE,
    BASE_URL: env.BASE_URL,
    PORT: env.PORT,
    ORIGIN: env.ORIGIN,
};
