apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-servicemonitor
  namespace: monitoring
  labels:
    release: monitoring   # חייב להתאים ל-helm release של kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: backend-release-backend-chart   # חייב להתאים ל-label של ה-Service
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http       # או שם הפורט אצלך ב-service, או להשתמש ב-targetPort: 8000
      path: /metrics   # רק אם באמת יש /metrics ב-backend
      interval: 15s
