replicaCount: 1

image:
  repository: abedabu28/backend-chart
  tag: "1.0"
  pullPolicy: IfNotPresent

containerPort: 8000

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: api.bilal-motors.local
      path: /
  tls: []   # مثال: - secretName: backend-tls  hosts: [api.example.com]

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
