apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ include "backend.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "backend.fullname" . }}
    spec:
      containers:
        - name: backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: {{ .Values.containerPort | default 8000 }}

          envFrom:
            - configMapRef:
                name: {{ include "backend.fullname" . }}-config
                optional: true
            - secretRef:
                name: {{ include "backend.fullname" . }}-secret
                optional: false

          readinessProbe:
            tcpSocket:
              port: {{ .Values.containerPort | default 8000 }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: {{ .Values.containerPort | default 8000 }}
            initialDelaySeconds: 15
            periodSeconds: 20
